#This is an example file to run compose
services:
  web:
    image: ghcr.io/jnunez2301/jellyfin-wireless-remote:latest
    container_name: jellyfin_wireless_remote
    ports:
      - "${SERVER_PORT:-8080}:3000"
    restart: unless-stopped
